# Site settings
title:              Jinny's Blog
email:              jinnysyuan@gmail.com
description:        "A blog for Jinny."
baseurl:            ""
url:                "https://jinnysyuan.github.io/"
title_description:  "寫寫文章，放些心得"
title_image:        "https://jinnysyuan.github.io/assets/img/logo.png"

google_analytics:   ""
disqus_account:     ""
github_repository:  "https://github.com/JinnySyuan"
addthis_id:         ""
post_limit:         5
logo:               "assets/img/logo.png"
background:         "assets/img/placeholder-big.jpg"
locale:             "zh-tw"

# Jekyll
# gems: [jekyll-paginate]
# paginate: 2
# paginate_path: "/posts/page:num/"

# Social usernames/URLs
twitter_username:
github_username:    JinnySyuan
instagram_username:
reddit_username:
linkedin_link:
google_plus_link:
stackoverflow_link:
xing_link:
facebook_link:

# Footer
footer_left:       ""
footer_right:      "Copyright © 2021 Jinny. All rights reserved."

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]

sass:
    sass_dir: assets/css